### ISSUE TITLE
SVG.defaults.trans is not provided in svg.js 2.2.5

### ISSUE THREAD

**Issue by nclsndr** [svgdotjs/svg.parser.js#4]
Due to the end of support of pathSegList I had to upgrade svg.js from 1.0.1-23-g095b474 to 2.2.5.
Other plugins are OK, but parser need a method .trans() not provided in core 2.*

14:27:  `def   = SVG.defaults.trans()`

I made a quick fix by adding the method into svg.js lib, it works in my case.

**Comment by Fuzzyma** [comment]
since this method is not used in the svg core once you should try to include the fix in the plugin and not in the core ;).

You can get a good approximation of the trans method by calling new `SVG.Matrix().extract()`
Which gives you `a-f`, `rotation`, `skew`, `translation` and `scale`

The only thing not included is the matrix itself which you can get with `new SVG.Matrix(element)`

You can even do `new SVG.Matrix(element).extract()` which already sets all values correctly.

In my opinion this plugin is not useful anymore anyway. You can get all values provided there with a simple `new SVG.Matrix(element).extract()` and `element.attr()`

**Comment by nclsndr** [comment]
Thank you Fuzzyma for your answer.
I didn't know the existence of `SVG.Matrix().extract()`
That's an old personal project I don't want to recode it, but I keep in mind your advices for the future.
